i5_object_name=SCHWEIZ ABSTIMMUNGEN GEMEINDEN ZIVILDIENSTGESETZ
i55_date_created=20260614
i120_caption=INFOGRAFIK - Eidgenoessische Volksabstimmung vom 14. Juni 2026 Resultate Gemeinden - Zivildienstgesetz. Diese Infografik wurde automatisiert vom Schreibroboter Lena erstellt.
i103_original_transmission_reference=
i90_city=
i100_country_code=CHE
i15_category=N
i105_headline=Politik
i25_keywords=
i40_special_instructions=Die Infografik kann im Grafikformat EPS und SVG bezogen werden. Diese Infografik wurde automatisiert vom Schreibroboter Lena erstellt.
i110_credit=KEYSTONE
i115_source=KEYSTONE
i80_byline=Lena
i122_writer=Lena
